actions/setup-ruby is deprecated and ruby version not found
>>>Run actions/setup-ruby@v1
  with:
    ruby-version: 2.7.2
------------------------
NOTE: This action is deprecated and is no longer maintained.
Please, migrate to https://github.com/ruby/setup-ruby, which is being actively maintained.
------------------------
Error: Version 2.7.2 not found